//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.17 at 05:41:22 ÏÂÎç CST 
//


package com.gome.test2.mt.test.req;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DT_TEST_Req complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DT_TEST_Req">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HEADER">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="INTERFACE_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DTSEND" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="XML_DATA">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TEST001" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="A" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="B" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="TEST002" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="A" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="B" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DT_TEST_Req", propOrder = {
    "header",
    "xmldata"
})
public class DTTESTReq {

    @XmlElement(name = "HEADER", required = true)
    protected DTTESTReq.HEADER header;
    @XmlElement(name = "XML_DATA", required = true)
    protected DTTESTReq.XMLDATA xmldata;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link DTTESTReq.HEADER }
     *     
     */
    public DTTESTReq.HEADER getHEADER() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link DTTESTReq.HEADER }
     *     
     */
    public void setHEADER(DTTESTReq.HEADER value) {
        this.header = value;
    }

    /**
     * Gets the value of the xmldata property.
     * 
     * @return
     *     possible object is
     *     {@link DTTESTReq.XMLDATA }
     *     
     */
    public DTTESTReq.XMLDATA getXMLDATA() {
        return xmldata;
    }

    /**
     * Sets the value of the xmldata property.
     * 
     * @param value
     *     allowed object is
     *     {@link DTTESTReq.XMLDATA }
     *     
     */
    public void setXMLDATA(DTTESTReq.XMLDATA value) {
        this.xmldata = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="INTERFACE_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DTSEND" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "interfaceid",
        "dtsend"
    })
    public static class HEADER {

        @XmlElement(name = "INTERFACE_ID", required = true)
        protected String interfaceid;
        @XmlElement(name = "DTSEND", required = true)
        protected String dtsend;

        /**
         * Gets the value of the interfaceid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINTERFACEID() {
            return interfaceid;
        }

        /**
         * Sets the value of the interfaceid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINTERFACEID(String value) {
            this.interfaceid = value;
        }

        /**
         * Gets the value of the dtsend property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDTSEND() {
            return dtsend;
        }

        /**
         * Sets the value of the dtsend property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDTSEND(String value) {
            this.dtsend = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TEST001" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="A" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="B" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="TEST002" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="A" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="B" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "test001",
        "test002"
    })
    public static class XMLDATA {

        @XmlElement(name = "TEST001")
        protected List<DTTESTReq.XMLDATA.TEST001> test001;
        @XmlElement(name = "TEST002")
        protected List<DTTESTReq.XMLDATA.TEST002> test002;

        /**
         * Gets the value of the test001 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the test001 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTEST001().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DTTESTReq.XMLDATA.TEST001 }
         * 
         * 
         */
        public List<DTTESTReq.XMLDATA.TEST001> getTEST001() {
            if (test001 == null) {
                test001 = new ArrayList<DTTESTReq.XMLDATA.TEST001>();
            }
            return this.test001;
        }

        /**
         * Gets the value of the test002 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the test002 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTEST002().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DTTESTReq.XMLDATA.TEST002 }
         * 
         * 
         */
        public List<DTTESTReq.XMLDATA.TEST002> getTEST002() {
            if (test002 == null) {
                test002 = new ArrayList<DTTESTReq.XMLDATA.TEST002>();
            }
            return this.test002;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="A" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="B" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "a",
            "b"
        })
        public static class TEST001 {

            @XmlElement(name = "A", required = true)
            protected String a;
            @XmlElement(name = "B", required = true)
            protected String b;

            /**
             * Gets the value of the a property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getA() {
                return a;
            }

            /**
             * Sets the value of the a property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setA(String value) {
                this.a = value;
            }

            /**
             * Gets the value of the b property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getB() {
                return b;
            }

            /**
             * Sets the value of the b property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setB(String value) {
                this.b = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="A" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="B" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "a",
            "b"
        })
        public static class TEST002 {

            @XmlElement(name = "A", required = true)
            protected String a;
            @XmlElement(name = "B", required = true)
            protected String b;

            /**
             * Gets the value of the a property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getA() {
                return a;
            }

            /**
             * Sets the value of the a property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setA(String value) {
                this.a = value;
            }

            /**
             * Gets the value of the b property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getB() {
                return b;
            }

            /**
             * Sets the value of the b property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setB(String value) {
                this.b = value;
            }

        }

    }

}
