//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.17 at 05:41:22 ÏÂÎç CST 
//


package com.gome.test2.mt.test.req;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gome.test2.mt.test.req package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MTTESTReq_QNAME = new QName("http://test2.gome.com", "MT_TEST_Req");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gome.test2.mt.test.req
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DTTESTReq }
     * 
     */
    public DTTESTReq createDTTESTReq() {
        return new DTTESTReq();
    }

    /**
     * Create an instance of {@link DTTESTReq.XMLDATA }
     * 
     */
    public DTTESTReq.XMLDATA createDTTESTReqXMLDATA() {
        return new DTTESTReq.XMLDATA();
    }

    /**
     * Create an instance of {@link DTTESTReq.HEADER }
     * 
     */
    public DTTESTReq.HEADER createDTTESTReqHEADER() {
        return new DTTESTReq.HEADER();
    }

    /**
     * Create an instance of {@link DTTESTReq.XMLDATA.TEST002 }
     * 
     */
    public DTTESTReq.XMLDATA.TEST002 createDTTESTReqXMLDATATEST002() {
        return new DTTESTReq.XMLDATA.TEST002();
    }

    /**
     * Create an instance of {@link DTTESTReq.XMLDATA.TEST001 }
     * 
     */
    public DTTESTReq.XMLDATA.TEST001 createDTTESTReqXMLDATATEST001() {
        return new DTTESTReq.XMLDATA.TEST001();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DTTESTReq }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://test2.gome.com", name = "MT_TEST_Req")
    public JAXBElement<DTTESTReq> createMTTESTReq(DTTESTReq value) {
        return new JAXBElement<DTTESTReq>(_MTTESTReq_QNAME, DTTESTReq.class, null, value);
    }

}
