//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.17 at 05:41:22 обнГ CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://test2.gome.com")
package com.gome.test2.mt.test.req;
